language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: cXkxEY6vloNTZzeQdLomXi/63czcMoC3U9OCZkuMaVQOpG/RWk7H738E8YXfn+GsB/pvPGLDJrf9lFPBvCdcEnJYP8T4RqpdT+hUKhUfUGKz+A1PoT9771Y15K6PS4Wt0gOlenqZWZjpAi1qG1fBOxoGfCobTA4wbpw1auOg+Pw=
  app: peaceful-plains-3044
  on:
    repo: shota817/enpit_travel


addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml