# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f779cdf8b3ddc543cb68e077c098a688d1eaf8ec27d510fe9843e342dbf43abe66c57cbdfa0bd198d002e90e614a822455d56e53244be568926b159f3ea833

test:
  secret_key_base: 04bae1fab8d055237cd1c282daa71b37f33bd70ae90c217f489f9abfd3f3b6b217e973aed9077fc6a19b376fd8249c674627c384408f2321a2bcc6d00601c504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
